# -*- coding: utf-8 -*-
"""
Created on Mon Sep 25 20:11:52 2017

@author: Administrator
"""

team_vars = ['teamId',
             'userId',
             'eventDate',
             'sessionType',
             'totalGRF',
             'optimalGRF',
             'irregularGRF',
             'control',
             'consistency',
             'symmetry',
             'grfProgramComposition',
             'totalAccelProgramComposition',
             'planeProgramComposition',
             'stanceProgramComposition',
             'AthleteStats',
             'userMass',
             'percLeftGRF',
             'percRightGRF',
             'percDistr',
             'totalAccel',
             'totalAccel',
             'irregularAccel',
             'hipSymmetry',
             'ankleSymmetry',
             'hipConsistency',
             'ankleConsistency',
             'consistencyLF',
             'consistencyRF',
             'hipControl',
             'ankleControl',
             'controlLF',
             'controlRF',
             'percOptimal']

athlete_vars = ['teamId',
                'userId',
                'eventDate',
                'sessionType',
                'totalGRF',
                'optimalGRF',
                'irregularGRF',
                'control',
                'consistency',
                'symmetry',
                'grfProgramComposition',
                'totalAccelProgramComposition',
                'planeProgramComposition',
                'stanceProgramComposition',
                'userMass', 'percLeftGRF',
                'percRightGRF',
                'percDistr',
                'totalAccel',
                'totalAccel',
                'irregularAccel',
                'hipSymmetry',
                'ankleSymmetry',
                'hipConsistency',
                'ankleConsistency',
                'consistencyLF',
                'consistencyRF',
                'hipControl',
                'ankleControl',
                'controlLF',
                'controlRF',
                'percOptimal']