# -*- coding: utf-8 -*-
"""
Created on Mon Sep 25 20:11:52 2017

@author: Administrator
"""

tg_vars = ['teamId',
           'trainingGroupId',
           'userId',
           'eventDate',
           'sessionType',
           'totalGRF',
           'optimalGRF',
           'irregularGRF',
           'control',
           'consistency',
           'symmetry',
           'grfProgramComposition',
           'totalAccelProgramComposition',
           'planeProgramComposition',
           'stanceProgramComposition',
           'AthleteStats',
           'singleLegGRF',
           'percLeftGRF',
           'percRightGRF',
           'percDistr',
           'totalAccel',
           'irregularAccel',
           'hipSymmetry',
           'ankleSymmetry',
           'hipConsistency',
           'ankleConsistency',
           'consistencyLF',
           'consistencyRF',
           'hipControl',
           'ankleControl',
           'controlLF',
           'controlRF',
           'percOptimal']

athlete_vars = ['teamId',
                'userId',
                'eventDate',
                'sessionType',
                'totalGRF',
                'optimalGRF',
                'irregularGRF',
                'control',
                'consistency',
                'symmetry',
                'grfProgramComposition',
                'totalAccelProgramComposition',
                'planeProgramComposition',
                'stanceProgramComposition',
                'trainingGroups',
                'userMass',
                'singleLegGRF',
                'percLeftGRF',
                'percRightGRF',
                'percDistr',
                'totalAccel',
                'irregularAccel',
                'hipSymmetry',
                'ankleSymmetry',
                'hipConsistency',
                'ankleConsistency',
                'consistencyLF',
                'consistencyRF',
                'hipControl',
                'ankleControl',
                'controlLF',
                'controlRF',
                'percOptimal']



tg_twomin_vars = ['twoMinuteIndex',
                  'sessionType',
                  'trainingGroupId',
                  'teamId',
                  'userId',
                  'eventDate',
                  'totalGRF',
                  'optimalGRF',
                  'irregularGRF',
                  'control',
                  'consistency',
                  'symmetry',
                  'athleteStats',
                  'LFgRF',
                  'RFgRF',
                  'singleLegGRF',
                  'percLeftGRF',
                  'percRightGRF',
                  'percDistr',
                  'totalAccel',
                  'irregularAccel',
                  'hipSymmetry',
                  'ankleSymmetry',
                  'hipConsistency',
                  'ankleConsistency',
                  'consistencyLF',
                  'consistencyRF',
                  'hipControl',
                  'ankleControl',
                  'controlLF',
                  'controlRF',
                  'percOptimal']


athlete_twomin_vars = ["twoMinuteIndex",
                        "sessionId",
                        "sessionType",
                        "timeStart",
                        "phaseLF",
                        "phaseRF",
                        "hipControl",
                        "controlLF",
                        "controlRF",
                        "hipSymmetry",
                        "ankleSymmetry",
                        "hipConsistency",
                        "consistencyLF",
                        "consistencyRF",
                        "trainingGroups",
                        "teamId",
                        "userId",
                        "eventDate",
                        "totalGRF",
                        "RFgRF",
                        "LFgRF",
                        "optimalGRF",
                        "irregularGRF",
                        "control",
                        "consistency",
                        "symmetry",
                        "totalAccumulatedGRF",
                        "optimalAccumulatedGRF",
                        "irregularAccumulatedGRF",
                        "userMass",
                        'leftGRF',
                        'rightGRF',
                        'singleLegGRF',
                        'percLeftGRF',
                        'percRightGRF',
                        'percDistr',
                        'totalAccel',
                        'irregularAccel',
                        'ankleConsistency',
                        'ankleControl',
                        'percOptimal']
